# 用线性回归算法来训练模型预测儿童身高

In [9]:
# 导入线型模型模块
from sklearn import linear_model
# 快速操作结构数组的工具
import numpy as np
# 导入复制模组
import copy
# 创建线型回归模型
reg1 = linear_model.LinearRegression()
# 训练数据，每一行表示一个样本，包含的信息分别为:
# 儿童年龄,性别（0表示女1表示男）
# 父亲、母亲、祖父、祖母、外祖父、外祖母的身高 单位:cm
X = np.array([[1, 1, 175, 160, 180, 155, 165, 170],
              [2, 1, 175, 160, 180, 155, 163, 170],
              [5, 1, 175, 160, 180, 155, 165, 170],
              [7, 1, 175, 160, 180, 155, 165, 170],
              [9, 0, 175, 160, 180, 158, 165, 170],
              [10, 1, 175, 168, 180, 155, 165, 170],
              [12, 1, 175, 160, 180, 155, 165, 170],
              [13, 1, 175, 160, 180, 155, 165, 170],
              [14, 0, 175, 160, 180, 155, 165, 170],
              [15, 1, 175, 160, 180, 155, 165, 170],
              [17, 1, 180, 160, 180, 155, 165, 170]])
# 儿童身高，单位:cm
y = np.array([55, 75, 105, 115, 130, 135, 155, 160, 164, 168, 175])

# 将训练模型X和y进行拟合操作
reg1.fit(X, y)

# 输出斜率，回归系数
print("训练模型的回归系数:",reg1.coef_)

# 输出训练模型的偏移或者截距，以下画线结束
print("训练模型的偏移或者截距:",reg1.intercept_)

# 设置测试组Xs的数据集,这里取了30组数据集作为测试
Xs = np.random.randint(0,2,size=(30,8))
# 设置年龄随机从1到18中随机取正整数
age = np.random.randint(1,18,size=(30))
Xs[:,0] = age
# 设置父亲身高为175到180的随机正整数
fa = np.random.randint(175,181,size=(30))
Xs[:,2] = fa
# 设置母亲身高为160到165的随机正整数
mo = np.random.randint(160,166,size=(30))
Xs[:,3] = mo
# 设置祖父身高为170到175的随机正整数
gdfu = np.random.randint(170,176,size=(30))
Xs[:,4] = gdfu
# 设置祖母身高为160到165的随机正整数
gdmo = np.random.randint(160,166,size=(30))
Xs[:,5] = gdmo
# 设置外祖父身高为170到175的随机正整数
mgdfu = np.random.randint(170,176,size=(30))
Xs[:,6] = mgdfu
# 设置外祖母身高为155到160的随机正整数
mgdmo = np.random.randint(155,161,size=(30))
Xs[:,7] = mgdmo
list = Xs[:,0]
print("测试数据集(训练数据)Xs:",Xs)

# 输出测试组的身高预测值
for item in Xs:
    item1 = copy.deepcopy(item)
    print('测试组:',item, '的预测身高为:', reg1.predict(item1.reshape(1,-1)))

训练模型的回归系数: [ 7.93555811e+00  3.33371692e+00 -3.22807825e+00 -7.39355581e-02
  4.44089210e-16  1.89259685e+00 -1.44649022e+00  0.00000000e+00]
训练模型的偏移或者截距: 574.9639432297677
测试数据集(训练数据)Xs: [[  7   0 178 161 174 160 175 156]
 [  2   0 178 164 170 163 172 156]
 [  9   1 178 164 170 161 173 155]
 [ 13   0 175 163 171 165 175 155]
 [ 17   1 178 165 171 165 170 156]
 [  2   0 176 163 175 163 173 159]
 [ 15   0 177 161 170 165 173 155]
 [  6   0 178 165 175 160 171 155]
 [  5   1 180 160 175 161 173 160]
 [ 17   0 179 160 173 161 171 157]
 [  4   1 178 162 172 165 172 155]
 [  7   1 177 162 173 162 172 157]
 [  7   0 176 160 172 162 173 157]
 [  4   0 178 160 173 163 170 159]
 [ 11   0 177 161 173 164 174 160]
 [ 10   0 177 161 175 161 175 159]
 [  7   1 180 162 170 161 175 156]
 [ 13   0 179 161 171 160 171 160]
 [  7   0 178 162 173 164 173 156]
 [ 11   1 176 160 174 165 172 158]
 [ 10   0 175 160 175 165 170 160]
 [ 14   0 180 162 173 165 173 155]
 [  3   0 175 162 173 163 172 159]
 [ 14  

# 用岭回归算法来训练模型预测儿童身高

In [10]:
# 创建岭回归模型
from sklearn.linear_model import Ridge
# 设置约束项系数为9.0,测试特征对结果的影响
reg2 = Ridge(alpha = 9.0)
# 同理,根据上述儿童组的x和y的数据进行拟合
reg2.fit(X,y)
# 输出预测结果
print("通过岭回归算法对测试组进行身高预测,当约束项系数为9.0时，预测的结果为 ↓ ")
for item in Xs:
    item2 = copy.deepcopy(item)
    print('测试组:',item, '的预测身高为:', reg2.predict(item2.reshape(1,-1)))

# 设置约束项系数为0.1,测试特征对结果的影响
# 其数值越大，特征对结果的影响越小
reg3 = Ridge(alpha = 0.1)
# 同理,根据上述儿童组的x和y的数据进行拟合
reg3.fit(X,y)
# 输出预测结果
print("通过岭回归算法对测试组进行身高预测,当约束项系数为0.1时，预测的结果为 ↓ ")
for item in Xs:
    item3 = copy.deepcopy(item)
    print('测试组:',item, '的预测身高为:', reg3.predict(item3.reshape(1,-1)))

通过岭回归算法对测试组进行身高预测,当约束项系数为9.0时，预测的结果为 ↓ 
测试组: [  7   0 178 161 174 160 175 156] 的预测身高为: [111.33612097]
测试组: [  2   0 178 164 170 163 172 156] 的预测身高为: [75.72984781]
测试组: [  9   1 178 164 170 161 173 155] 的预测身高为: [126.22352518]
测试组: [ 13   0 175 163 171 165 175 155] 的预测身高为: [162.53014022]
测试组: [ 17   1 178 165 171 165 170 156] 的预测身高为: [186.41044411]
测试组: [  2   0 176 163 175 163 173 159] 的预测身高为: [79.02208393]
测试组: [ 15   0 177 161 170 165 173 155] 的预测身高为: [173.64891553]
测试组: [  6   0 178 165 175 160 171 155] 的预测身高为: [103.69698568]
测试组: [  5   1 180 160 175 161 173 160] 的预测身高为: [93.43674002]
测试组: [ 17   0 179 160 173 161 171 157] 的预测身高为: [183.04692484]
测试组: [  4   1 178 162 172 165 172 155] 的预测身高为: [91.05873149]
测试组: [  7   1 177 162 173 162 172 157] 的预测身高为: [113.36676101]
测试组: [  7   0 176 160 172 162 173 157] 的预测身高为: [115.14148329]
测试组: [  4   0 178 160 173 163 170 159] 的预测身高为: [89.96693656]
测试组: [ 11   0 177 161 173 164 174 160] 的预测身高为: [143.96101166]
测试组: [ 10   0 177 161 175 161 175 1

# 用Lasso回归算法来训练模型预测儿童身高

In [13]:
# 创建Lasso回归模型
from sklearn.linear_model import Lasso
# 设置惩罚项系数为8.0
reg4 = Lasso(alpha = 8.0)
# 同理,根据上述儿童组的x和y的数据进行拟合
reg4.fit(X,y)
# 输出预测结果
print("通过Lasso回归算法对测试组进行身高预测,当惩罚项系数为8.0时，预测的结果为 ↓ ")
for item in Xs:
    item4 = copy.deepcopy(item)
    print('测试组:',item, '的预测身高为:', reg4.predict(item4.reshape(1,-1)))

# 设置惩罚项系数为0.8
reg5 = Lasso(alpha = 0.8)
# 同理,根据上述儿童组的x和y的数据进行拟合
reg5.fit(X,y)
print("通过Lasso回归算法对测试组进行身高预测,当惩罚项系数为0.8时，预测的结果为 ↓ ")
for item in Xs:
    item5 = copy.deepcopy(item)
    print('测试组:',item, '的预测身高为:', reg5.predict(item5.reshape(1,-1)))

通过Lasso回归算法对测试组进行身高预测,当惩罚项系数为8.0时，预测的结果为 ↓ 
测试组: [  7   0 178 161 174 160 175 156] 的预测身高为: [112.67227979]
测试组: [  2   0 178 164 170 163 172 156] 的预测身高为: [77.38568653]
测试组: [  9   1 178 164 170 161 173 155] 的预测身高为: [126.7869171]
测试组: [ 13   0 175 163 171 165 175 155] 的预测身高为: [155.01619171]
测试组: [ 17   1 178 165 171 165 170 156] 的预测身高为: [183.24546632]
测试组: [  2   0 176 163 175 163 173 159] 的预测身高为: [77.38568653]
测试组: [ 15   0 177 161 170 165 173 155] 的预测身高为: [169.13082902]
测试组: [  6   0 178 165 175 160 171 155] 的预测身高为: [105.61496114]
测试组: [  5   1 180 160 175 161 173 160] 的预测身高为: [98.55764249]
测试组: [ 17   0 179 160 173 161 171 157] 的预测身高为: [183.24546632]
测试组: [  4   1 178 162 172 165 172 155] 的预测身高为: [91.50032383]
测试组: [  7   1 177 162 173 162 172 157] 的预测身高为: [112.67227979]
测试组: [  7   0 176 160 172 162 173 157] 的预测身高为: [112.67227979]
测试组: [  4   0 178 160 173 163 170 159] 的预测身高为: [91.50032383]
测试组: [ 11   0 177 161 173 164 174 160] 的预测身高为: [140.9015544]
测试组: [ 10   0 177 161 175 161 175

# 用弹性网络算法来训练模型预测儿童身高

In [17]:
# 创建ElasticNet模型
from sklearn.linear_model import ElasticNet
# 设置验证参数为 l1_ratio 为随机取值(0到1范围内)
lr = np.random.rand()
# 设置测试参数alpha = 8.0
reg6 = ElasticNet(alpha = 8.0,l1_ratio = lr)
# 同理，先进行拟合
reg6.fit(X,y)
# 输出预测结果
print("通过弹性网络ElasticNet算法对测试组进行身高预测,当 alpha = 8.0 l1_ratio = ",lr,"时，预测的结果为 ↓ ")
for item in Xs:
    item6 = copy.deepcopy(item)
    print('测试组:',item, '的预测身高为:', reg6.predict(item6.reshape(1,-1)))

# 设置测试参数alpha = 0.8
reg7 = ElasticNet(alpha = 0.8,l1_ratio = lr)
# 同理，先进行拟合
reg7.fit(X,y)
# 输出预测结果
print("通过弹性网络ElasticNet算法对测试组进行身高预测,当 alpha = 0.8 l1_ratio = ",lr,"时，预测的结果为 ↓ ")
for item in Xs:
    item7 = copy.deepcopy(item)
    print('测试组:',item, '的预测身高为:', reg7.predict(item7.reshape(1,-1)))




通过弹性网络ElasticNet算法对测试组进行身高预测,当 alpha = 8.0 l1_ratio =  0.3047579334577363 时，预测的结果为 ↓ 
测试组: [  7   0 178 161 174 160 175 156] 的预测身高为: [115.43129751]
测试组: [  2   0 178 164 170 163 172 156] 的预测身高为: [85.56420332]
测试组: [  9   1 178 164 170 161 173 155] 的预测身高为: [127.37813518]
测试组: [ 13   0 175 163 171 165 175 155] 的预测身高为: [151.27181053]
测试组: [ 17   1 178 165 171 165 170 156] 的预测身高为: [175.16548588]
测试组: [  2   0 176 163 175 163 173 159] 的预测身高为: [85.56420332]
测试组: [ 15   0 177 161 170 165 173 155] 的预测身高为: [163.2186482]
测试组: [  6   0 178 165 175 160 171 155] 的预测身高为: [109.45787867]
测试组: [  5   1 180 160 175 161 173 160] 的预测身高为: [103.48445983]
测试组: [ 17   0 179 160 173 161 171 157] 的预测身高为: [175.16548588]
测试组: [  4   1 178 162 172 165 172 155] 的预测身高为: [97.51104099]
测试组: [  7   1 177 162 173 162 172 157] 的预测身高为: [115.43129751]
测试组: [  7   0 176 160 172 162 173 157] 的预测身高为: [115.43129751]
测试组: [  4   0 178 160 173 163 170 159] 的预测身高为: [97.51104099]
测试组: [ 11   0 177 161 173 164 174 160] 的预测身高为: [139